### ISSUE TITLE
--json output not properly formatted?

### ISSUE THREAD

**Issue by high101bro** [countercept/chainsaw#10]
I saved the results as a json file. I believe there's a format error somewhere. When I paste the contents into a json syntax verifier it fails, and when I import it into PowerShell and convert it, it also fails.

.\chainsaw.exe hunt .\evtx_attack_samples\Execution\exec_persist_rundll32_mshta_scheduledtask_sysmon_1_3_11.evtx --rules .\sigma_rules\ --mapping .\mapping_files\sigma-mapping.yml --lateral-all --json .\results.json

Get-Content -raw .\results.json | ConvertFrom-Json
// Fails

**Comment by alexkornitzer** [comment]
This is already fixed in master and will be out in the next release.

**Comment by fscc-jamesd** [comment]
V1.0.1 has been released.

Running the with same commands as above now results in the expected output:

![image](https://user-images.githubusercontent.com/71783749/132092894-dc71c257-4283-426d-8efe-b11668d2dcce.png)
