### ISSUE TITLE
killed by security tools

### ISSUE THREAD

**Issue by zengjie1** [countercept/chainsaw#14]
Symantec category: Malware
Hash: 90A88E340271274B9BFF5502C34E4669CD450FD6286625E827FB66019A9F1B6B

**Comment by fscc-jamesd** [comment]
Hi @zengjie1 

I raised this to Symantec and they've confirmed that it's a false positive and they will whitelist it. However, if they've just whitelisted via Hash then there's a good chance this may happen again in the future. Unfortunately there's very little that I can do about this.

![image](https://user-images.githubusercontent.com/71783749/132601606-d103fd98-e5c8-4fa2-85af-53c1eca18fb6.png)
