### ISSUE TITLE
EventID in Sigma Rules not matching (String vs Numeric)

### ISSUE THREAD

**Issue by stdio-h** [countercept/chainsaw#19]
Most sigma rules use numeric EventID - i.e.:

<pre>detection:
    selection:
        EventID: 7045
        ServiceName:
            - 'srservice'
            - 'ipvpn'
            - 'hkmsvc'
    condition: selection</pre>

modules.rs [line 215] however converts the EventID to a String 

<pre>doc["EventID"] = json!(event_id.to_string());</pre>

and the condition (EventID: 7045) is therefore not met. After removing the conversion to String (or rewriting the Sigma Rule to `EventID: "7045"`) the Event is successfully matched:

<pre>doc["EventID"] = json!(event_id);</pre>

**Comment by michaelgoodman-cr** [comment]
_delete if this doesn't have a place here but_
As a temporary solution, the following can transform the sigma rule data set:
```
for f in $(find sigma_rules/ -name '*.yml'); do sed -i 's/\(EventID:\s*\)\([[:digit:]]\{4\}\)/\1"\2"/' $f; echo transforming $f; done
```

**Comment by Yeti-Sec** [comment]
Thanks for the doing the leg work on that Michael. I just put this together for the nest event ID statements using the loop you put together

`'s/\(- \)\([[:digit:]]\{1,5\}\)/\1"\2"/'`
