### ISSUE TITLE
Valid JSON Output

### ISSUE THREAD

**Issue by weslambert** [countercept/chainsaw#2]
Great work on this! I really appreciate all the work that went into it!

While the individual objects contained within the JSON output are considered valid JSON, it seems like when they are concatenated together in the results file, they are not separated (by comma `,`), and/or considered as an array of objects (with open/closing bracket `[]`), so the results can't be picked up by tools that parse JSON without additional work. If needed, I can follow up with a PR as I get time.

Additionally, it would be nice to consider allowing for JSON output to stdout, so a file would not need to be written to disk, but other tools could easily parse the data returned.

**Comment by fscc-alexkornitzer** [comment]
The above should fix the json issue, I think we will then create a new issue to track the stdout support for piping purposes as an enhancement.

**Comment by weslambert** [comment]
> The above should fix the json issue, I think we will then create a new issue to track the stdout support for piping purposes as an enhancement.

Sounds good, thanks!
