### ISSUE TITLE
"+" at the start of detection_rules column values

### ISSUE THREAD

**Issue by michaeljgoodman** [countercept/chainsaw#33]
Even when only a single rule matches, testing numerous sets of logs will often come back with "+ Accessing WinAPI in PowerShell" or something similar, where the + character is added to the start of the column value.

I'm unsure if this is because there may be one or more rules in the main sigma ruleset that don't have a title, but even in that case it would be preferable to exclude the empty " +" from the start.

_As a small compatibility sidenote, this does then interfere with opening the csv outputs in excel as excel will turn these column values into equations, which is actually quite difficult to get around without some transformation of the file._

**Comment by fscc-jamesd** [comment]
Hi @michaeljgoodman 

Thanks for raising this issue. 

Just to make sure I'm understanding this issue correctly, the "+" is the 'rule prefix' that is used to delimit the start of each new rule that has fires. It will appear at the start of every rule name. So in the example you showed above there is only one total rule "Accessing WinAPI in powershell" that has fired. Does this still cause an issue for you?

Nice spot on the "+" causing issues in excel, I'll add a fix to exclude the rule prefix when outputting to a CSV file

**Comment by michaeljgoodman** [comment]
Ah okay. If this is a prefix then it's working correctly. I misunderstood it as a character placed _between_ rule names.

In which case, just excluding it from the csv output would be perfect.

**Comment by alexkornitzer** [comment]
This is addressed in 2.0.0-alpha.1
