### ISSUE TITLE
CSV Files not generated correctly

### ISSUE THREAD

**Issue by juaromu** [countercept/chainsaw#35]
When \r present in columns, the CSV files generate additional lines and not formatted correctly:

system_time,id,detection_rules,computer_name,Event.EventData.TargetFilename,image
2021-10-26 05:58:04,11,"+ Suspicious xxxx
File Created In TMP","""xxxx""",xxxx,xxxx
2021-10-26 06:55:36,11,"+ Suspicious xxxx
File Created In TMP","""xxxx""",xxxx,xxxx

This is normally the case for the column "Detection Rules".
Would it be possible to remove that \r or generate that column in a different way so that the CSVs will be created correctly?

**Comment by alexkornitzer** [comment]
Yeah this is on the list. The formatting done to present in the cli is not stripped on csv output. This is a bug.

**Comment by juaromu** [comment]
Thank you

**Comment by alexkornitzer** [comment]
I think I have fixed this in 2.0.0-alpha.1
