### ISSUE TITLE
Output Directory option? 

### ISSUE THREAD

**Issue by johnathan-fern** [countercept/chainsaw#36]
Curious as to why there isn't an option for both hunt/search for an output directory? 

I use this for multiple concurrent clients and it creates a lot of overhead to either move chainsaw and its libraries needed, or constantly moving the folder created from where chainsaw executes to my current working directory

**Comment by alexkornitzer** [comment]
Chainsaw has the `--output` option so I am not sure what you are asking for here exactly. Would you be able to elaborate further?

**Comment by alexkornitzer** [comment]
As this is definitely fixed in v2.0.0-alpha.x, I am closing this issue.
