### ISSUE TITLE
Is there any installation guide?

### ISSUE THREAD

**Issue by Blason** [countercept/chainsaw#42]
I cloned the repository and tried compiling the software but unfortunately I did not find any relevant document to do so. Am I missing anything or looking at wrong place? My OS is Ubuntu-20.04

**Comment by AndrewRathbun** [comment]
Try the Releases?

https://github.com/countercept/chainsaw/releases/tag/v1.1.2

**Comment by Blason** [comment]
I guess I downloaded the same one. But I feel I downloaded source codes. Thanks for pointer
