### ISSUE TITLE
Give it a bit of a clean and add some very much needed tests :P

### ISSUE THREAD

**Issue by fscc-alexkornitzer** [countercept/chainsaw#43]
So IMO the chainsaw code needs a bit of a clean. We also need to add tests so that its easier for contributions and changes. When I find some time I will try and make some headway into this.

- [x] Refactor to handle Rust style testing
- [ ] Clean code as required

**Comment by fscc-alexkornitzer** [comment]
Going to start with tests first because that will make the refactor and clean easier.

**Comment by alexkornitzer** [comment]
No longer going to keep this open as we are tracking this in v2.
