### ISSUE TITLE
Request for time filters(start and end dates) in local time

### ISSUE THREAD

**Issue by termcap** [countercept/chainsaw#45]
It would be great to have the start and end date filters support the local machine time as apart from servers most desktops in an organization would have local time set.

Currently the events returned with date filters set are also in UTC time which means one needs to reconvert back the output to local time.

**Comment by alexkornitzer** [comment]
I'll look into this.

**Comment by alexkornitzer** [comment]
Working on this now, just to clarify, are you wanting chainsaw to mutate the timestamp column to the local time on output?

**Comment by alexkornitzer** [comment]
This is addressed in v2.0.0-alpha.0
