### ISSUE TITLE
Support for Syslog/CEF output

### ISSUE THREAD

**Issue by Richard1611** [countercept/chainsaw#46]
Request to add support for sending the output as Syslog or CEF stream.

This would give the possibility of performing threat hunting on multiple teams at the same time without the need for forensic acquisitions.

Example:

1-Display chainsaw on a big grouf of computers (Ex: 1000)
2-Execute a chainsaw command on multiple computers. (Example: With psexec.)
3-Receive all the data in a SIEM and query about them.

**Comment by fscc-jamesd** [comment]
Hi @Richard1611 

Unfortunately chainsaw is not designed to centralise logs, there are better tools that can achieve this. An approach you might want to consider is to enable windows event forwarding (WEF) and then run chainsaw against the logs which have been collected in a central location. 

Unfortunately there appears to be an issue with the underlying rust evtx library which means that forwarded events currently can't be processed (as discussed in #25 ) but once this is fixed the solution above should work for you.

**Comment by georgethemarmot** [comment]
Hi @Richard1611 
WEF is efficient to centralize, but the forwarded event file is big (eg > 20GB) it will be really slow to process or filter.
If you want to split the collection evtx file by source you have to change and recompile the event collection dll and MS documentation is missing. 
I suggest to look into SIEM solutions. 
https://github.com/wazuh/wazuh is a free solution if you have time to fiddle around with configurations.
