### ISSUE TITLE
How to install on Windows 10

### ISSUE THREAD

**Issue by bmmojo** [countercept/chainsaw#67]
Hey, a beginner at this I was wondering if anyone could help me install this on my Windows 10? 
I'm really not getting it... Thanks in advance!

**Comment by AndrewRathbun** [comment]
There is nothing to install. You simply run the tool from the command line. Let me know if you have further questions beyond that.

**Comment by FranticTyping** [comment]
Hi @bmmojo 

As mentioned above, there's nothing to install for this tool. You can download the latest compiled version of chainsaw from the releases page: https://github.com/countercept/chainsaw/releases

You can then just unzip the binary and run the tool directly. Feel free to re-open this issue if you have any issues.

**Comment by bmmojo** [comment]
Hey @FranticTyping @AndrewRathbun Thanks for the reply. Apology for replying back so late.

I downloaded chainsaw_8664-pc-windows-msvc.zip  however when I run chainsaw.exe nothing shows up unfortunately am I missing something?

**Comment by AndrewRathbun** [comment]
@bmmojo you need to run it from the command line, like this:

![cmd_7Q3QZIb8H6](https://user-images.githubusercontent.com/36825567/157920835-fe803f22-c9ac-46bf-832f-1afa9cb69cc6.gif)

You can see the help info for the subcommands by doing this:

![cmd_tmqJD4nFXC](https://user-images.githubusercontent.com/36825567/157921365-631cdb31-461d-4c62-ba29-daa3ee09437e.gif)

**Comment by bmmojo** [comment]
@AndrewRathbun

Ah awesome! Thank you for showing me! :)
