### ISSUE TITLE
failed to parse manifest at

### ISSUE THREAD

**Issue by purplebyteone** [countercept/chainsaw#76]
![image](https://user-images.githubusercontent.com/17739404/168444840-34997165-01a0-43dd-b318-684b7a5b72a6.png)

**Comment by alexkornitzer** [comment]
Looks like a `rust` problem to me, what version of rust are you using to compile chainsaw in the above?

**Comment by purplebyteone** [comment]
rustc 1.48.0

**Comment by alexkornitzer** [comment]
Right, yep my guess there is that the rust version is too old. I would recommend grabbing it from rustup https://rustup.rs/ then you should be good to go.
