### ISSUE TITLE
--skip-errors fails on File System errors

### ISSUE THREAD

**Issue by dsplice** [countercept/chainsaw#90]
It appears that issue #49 https://github.com/countercept/chainsaw/issues/49#issue-1072543106 has returned.  This is with V2.0.0-beta.2

**Comment by alexkornitzer** [comment]
I can't seem to replicate this, are you able to show the output you got and the command you ran so I can hopefully use that to work out what is going on?

<img width="839" alt="Screenshot 2022-07-22 at 14 59 11" src="https://user-images.githubusercontent.com/2750747/180455223-ebc5c26c-1ad1-4dcd-aaeb-48c70aea919d.png">

**Comment by alexkornitzer** [comment]
This should be fixed in `2.0.0-beta.3` assuming I have caught the right bug, please could you check if this build fixes it?

**Comment by dsplice** [comment]
![image](https://user-images.githubusercontent.com/1919754/180565613-bfc2dc95-c4dd-47d4-8737-9665a624d60b.png)

**Comment by alexkornitzer** [comment]
Ah damn, thanks for the above though, can see exactly where that has fallen into. Right lets see if I managed to fix the above with beta 4! Apologies for the build spam.

**Comment by dsplice** [comment]
All good!  Happy to help in any little way I can.

**Comment by alexkornitzer** [comment]
Did that work? Happy for me to close this issue out?

**Comment by dsplice** [comment]
I just downloaded to try it.  Seems Windows Defender detects it as malware.

![image](https://user-images.githubusercontent.com/1919754/180636382-486a1f04-1902-463e-ae04-0ce1a30ce967.png)

**Comment by alexkornitzer** [comment]
Weird it should only potentially think its malware if it the zip containing the attack samples too. Which it doesn't look like you downloaded in the above.

**Comment by dsplice** [comment]
Latest update of the malware definitions fixed the false positive.  However the error is still there.

**Comment by alexkornitzer** [comment]
Good you got that sorted, but ah damn, okay still the same error message as you posted above?

**Comment by alexkornitzer** [comment]
Okay I am a tad stumped with this one as I just booted my windows VM and pointed Chainsaw at the `C:\` drive and it ran through to the end when `--skip-errors` was enabled. Just to double check based on the `(1)` in your screenshot above, you definitely ran beta 4 and not 3 right?

<img width="1054" alt="Screenshot 2022-07-24 at 11 13 04" src="https://user-images.githubusercontent.com/2750747/180642399-a7a23a77-2207-45b5-a210-cebd76f096f7.png">

**Comment by dsplice** [comment]
I verified the version, beta 4.  This was run against a vhdx, so that could be an issue too.  If it works everywhere else (and seems to), I would just chalk it up to a weird edge case.

**Comment by alexkornitzer** [comment]
What error message are you getting now, because if its a different one, then it will be a different code path we have not caught. If it is the same error message then I am very confused because I am about 90% sure that I have caught that one. But yep worst case we can close this out until it happens again, but I would prefer to get it squashed.

**Comment by dsplice** [comment]
Same exact error.  I can provide screenshot tomorrow.

**Comment by alexkornitzer** [comment]
Okay lets have a look tomorrow, you might have to just let me know what you are running on and I will try and replicate that as close as possible but that error message is definitely guarded away now.

https://github.com/countercept/chainsaw/blob/master/src/file/mod.rs#L299-L302
```
    } else if skip_errors {
        cs_eyellowln!("[!] Specified path does not exist - {}", path.display());
    } else {
        anyhow::bail!("Specified event log path is invalid - {}", path.display());
    }
```

**Comment by dsplice** [comment]
I am running it on a KAPE triage image (VHDX) taken from a full disk image (E01).  Here is a screenshot of the root directory.

![image](https://user-images.githubusercontent.com/1919754/180863452-dd9390ea-b151-437f-8178-3922a57d2c90.png)

**Comment by FranticTyping** [comment]
Hey @dsplice 

Thanks for sending over the screenshot, the helps.

Just to make sure we’re all on the same page, could you send across a screenshot showing the full command you’re using and the error you see, and also a screenshot of the output of `chainsaw.exe —version` please?

Thanks!

**Comment by dsplice** [comment]
![image](https://user-images.githubusercontent.com/1919754/180869037-cfe2eb88-a538-4db9-921f-7ced8ed1e7f5.png)

If I run it with the target of D:/D (subdirectory without System Volume Info) it runs fine.  Just on the SVI directory.

**Comment by FranticTyping** [comment]
@dsplice that's great, thanks!

Can you try running that command again with the `--skip-errors` flag, e.g:

```
chainsaw hunt D: -s sigma/ -m mappings/sigma-event-logs-all.yml -r rules/ --skip-errors
```

That should allow Chainsaw to continue past that error, which I think is what you want?

**Comment by dsplice** [comment]
Darn, I must have missed that in the last testing.  Ignore me.  It works fine now  😊

**Comment by FranticTyping** [comment]
Glad to hear it's all working well, thanks for helping us troubleshoot!
